// Single source of truth for how images are shipped: the per-extension weight
// budget of the stored originals, and the responsive widths generated from
// them at build time.
//
// Budgets are enforced by tests/unit/image-budget.test.js; bring a violating
// file within budget with `npm run compress-images`.
//
// Cover images render in a ~256px-tall banner (post.njk) and as card
// thumbnails, so anything beyond these limits is wasted bytes on every
// page view.
const path = require('path');

const BUDGETS = {
  '.png': 700 * 1024,
  '.jpg': 400 * 1024,
  '.jpeg': 400 * 1024,
  '.webp': 300 * 1024,
  '.gif': 1100 * 1024, // legacy animated gif in a 2019 post; do not add more
  '.svg': 100 * 1024,
  '.ico': 50 * 1024,
};

// Directories whose images are scanned/compressed against BUDGETS. The wedding
// archive (archive/wedding/img) ships full-size photos and used to escape the
// budget entirely, which is how the repo bloated — keep it in this list.
const IMAGE_DIRS = [
  path.join(__dirname, '..', 'src', 'assets', 'images'),
  path.join(__dirname, '..', 'archive', 'wedding', 'img'),
];

// Responsive srcset widths generated by the eleventy-img transform in
// .eleventy.js. The content column is `max-w-4xl` (896px), so 1200 covers a
// wide viewport at >1x DPR and 400 covers a phone; a source narrower than a
// listed width is never upscaled.
//
// Weight budgets alone cannot catch the failure these fix: a 1408x768 cover is
// comfortably inside the 700 KB .png budget and still ~3x the resolution of
// the card it renders into. `uses-responsive-images` in lighthouserc.json is
// what gates that.
const IMAGE_WIDTHS = [400, 800, 1200];

// Default `sizes` for generated <picture> elements: images span the content
// column, which is 896px wide at most. Per-image overrides (e.g. the 192px
// profile avatar) are set as a `sizes` attribute in the template.
const IMAGE_SIZES = '(max-width: 896px) 100vw, 896px';

module.exports = { BUDGETS, IMAGE_DIRS, IMAGE_WIDTHS, IMAGE_SIZES };
